services:
  web:
    build: .
    command: bash /apps/startup/app.sh
    env_file:
      - local.env
    ports:
      - "8086:8080"
    volumes:
      - ./deployment/settings/env/:/apps/settings/env/
      - ./deployment/settings/secrets/:/apps/settings/secrets/
      - ./deployment/conf:/apps/deployment/conf/
  test:
    build: .
    command: bash /apps/startup/test.sh
    environment:
      MIN_COVERAGE: 90
    volumes:
      - ./deployment/settings/env:/apps/settings/env
      - ./deployment/settings/secrets:/apps/settings/secrets
      - ./deployment/settings/test:/apps/settings/test
      - ./tests:/apps/app/tests
      - ./coverage:/apps/coverage/